Algoritmo "pontofinal"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/04/2025
Var
// Seção de Declarações das variáveis 
a: inteiro
b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-5
b<-2
escreval (a+b)
escreval (a-b)
escreval (a*b)
escreval (a/b)
escreval (a\b)
escreval (a^b)
escreval (a%b)
Fimalgoritmo
