Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2025
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Escreva um valor:")
leia (valor)

//Condicional Simples

se (valor < 10) entao

escreval ("O valor é menor que 10")
senao
escreval ("Ronaldo")
fimse
Fimalgoritmo
