Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/05/2025
Var
// Seção de Declarações das variáveis 
numero, numero2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero <- 0
 enquanto (numero <= 5) faca
   aleatorio on
   leia(numero2)
   aleatorio off
   numero <- numero + 1
  fimenquanto
Fimalgoritmo