Algoritmo "pontofinal"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/04/2025
Var
// Seção de Declarações das variáveis 
n2: real
n1: real
n3:real
media: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n1<-12
n2<-23
n3<-15
media <- (n1+n2+n3)/3
escreval ("A média dos dois numeros é igual a: ", media)
Fimalgoritmo
